name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install --force

      - name: 'Create env file'
        run: |
          touch .env
          echo VITE_APP_ID=${{ secrets.VITE_APP_ID }} >> .env
          echo VITE_API_KEY=${{ secrets.VITE_API_KEY }} >> .env
          echo VITE_EMAIL_KEY=${{ secrets.VITE_EMAIL_KEY }} >> .env
          echo VITE_EMAIL_SERVICE_ID=${{ secrets.VITE_EMAIL_SERVICE_ID }} >> .env
          echo VITE_EMAIL_TEMPLATE_ID=${{ secrets.VITE_EMAIL_TEMPLATE_ID }} >> .env
          cat .env

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}